package com.jskierbi.transitionsdemo;

/**
 * Created by jakub on 04/30/2015.
 */
public class Data {

	public static final ImageModel[] IMAGE_DATA = {
			new ImageModel(R.drawable.a001, "Road", "Activity transitions in material design apps provide visual connections between different states through motion and transformations between common elements. You can specify custom animations for enter and exit transitions and for transitions of shared elements between activities.", "Uploaded on 3.04 by XYZ"),
			new ImageModel(R.drawable.a002, "Nenufars", "Activity transitions in material design apps provide visual connections between different states through motion and transformations between common elements. You can specify custom animations for enter and exit transitions and for transitions of shared elements between activities.", "Uploaded on 3.04 by XYZ"),
			new ImageModel(R.drawable.a003, "Mountain & sky", "Activity transitions in material design apps provide visual connections between different states through motion and transformations between common elements. You can specify custom animations for enter and exit transitions and for transitions of shared elements between activities.", "Uploaded on 3.04 by XYZ"),
			new ImageModel(R.drawable.a004, "Sea sunset", "Activity transitions in material design apps provide visual connections between different states through motion and transformations between common elements. You can specify custom animations for enter and exit transitions and for transitions of shared elements between activities.", "Uploaded on 3.04 by XYZ"),
			new ImageModel(R.drawable.a005, "Palm tree", "Activity transitions in material design apps provide visual connections between different states through motion and transformations between common elements. You can specify custom animations for enter and exit transitions and for transitions of shared elements between activities.", "Uploaded on 3.04 by XYZ"),
			new ImageModel(R.drawable.a006, "Some nuts", "Activity transitions in material design apps provide visual connections between different states through motion and transformations between common elements. You can specify custom animations for enter and exit transitions and for transitions of shared elements between activities.", "Uploaded on 3.04 by XYZ"),
			new ImageModel(R.drawable.a007, "Green lake leafs", "Activity transitions in material design apps provide visual connections between different states through motion and transformations between common elements. You can specify custom animations for enter and exit transitions and for transitions of shared elements between activities.", "Uploaded on 3.04 by XYZ"),
			new ImageModel(R.drawable.a008, "Red beach", "Activity transitions in material design apps provide visual connections between different states through motion and transformations between common elements. You can specify custom animations for enter and exit transitions and for transitions of shared elements between activities.", "Uploaded on 3.04 by XYZ"),
			new ImageModel(R.drawable.a009, "Sky mountains", "Activity transitions in material design apps provide visual connections between different states through motion and transformations between common elements. You can specify custom animations for enter and exit transitions and for transitions of shared elements between activities.", "Uploaded on 3.04 by XYZ"),
			new ImageModel(R.drawable.a010, "Mountain river", "Activity transitions in material design apps provide visual connections between different states through motion and transformations between common elements. You can specify custom animations for enter and exit transitions and for transitions of shared elements between activities.", "Uploaded on 3.04 by XYZ"),
			new ImageModel(R.drawable.a011, "Seashore", "Activity transitions in material design apps provide visual connections between different states through motion and transformations between common elements. You can specify custom animations for enter and exit transitions and for transitions of shared elements between activities.", "Uploaded on 3.04 by XYZ"),
			new ImageModel(R.drawable.a012, "Trees", "Activity transitions in material design apps provide visual connections between different states through motion and transformations between common elements. You can specify custom animations for enter and exit transitions and for transitions of shared elements between activities.", "Uploaded on 3.04 by XYZ"),
			new ImageModel(R.drawable.a013, "Yellow flower", "Activity transitions in material design apps provide visual connections between different states through motion and transformations between common elements. You can specify custom animations for enter and exit transitions and for transitions of shared elements between activities.", "Uploaded on 3.04 by XYZ"),
			new ImageModel(R.drawable.a014, "Sky clouds", "Activity transitions in material design apps provide visual connections between different states through motion and transformations between common elements. You can specify custom animations for enter and exit transitions and for transitions of shared elements between activities.", "Uploaded on 3.04 by XYZ"),
			new ImageModel(R.drawable.a015, "Beautiful sea sunset", "Activity transitions in material design apps provide visual connections between different states through motion and transformations between common elements. You can specify custom animations for enter and exit transitions and for transitions of shared elements between activities.", "Uploaded on 3.04 by XYZ"),
			new ImageModel(R.drawable.a016, "Abstract nature", "Activity transitions in material design apps provide visual connections between different states through motion and transformations between common elements. You can specify custom animations for enter and exit transitions and for transitions of shared elements between activities.", "Uploaded on 3.04 by XYZ"),
			new ImageModel(R.drawable.a017, "Timber", "Activity transitions in material design apps provide visual connections between different states through motion and transformations between common elements. You can specify custom animations for enter and exit transitions and for transitions of shared elements between activities.", "Uploaded on 3.04 by XYZ"),
			new ImageModel(R.drawable.a018, "Yellow flowers", "Activity transitions in material design apps provide visual connections between different states through motion and transformations between common elements. You can specify custom animations for enter and exit transitions and for transitions of shared elements between activities.", "Uploaded on 3.04 by XYZ")};
}
